### ISSUE TITLE
Sentry.configureScope scope.setUser not working

### ISSUE THREAD

**Issue by illume** [expo/sentry-expo#56]
Docs: https://docs.sentry.io/enriching-error-data/scopes/?platform=javascript#configuring-the-scope

Code to reproduce:
```javascript
Sentry.configureScope((scope) => {
	scope.setUser({
	  username: 'joeblogs'
	});
});
```

Error reported.

```
_sentryExpo.default.configureScope is not a function. (In '_sentryExpo.default.configureScope(function (scope) {
            scope.setUser({
              username: 'joeblogs'
            });
          })', '_sentryExpo.default.configureScope' is undefined)

```

**Comment by HazAT** [comment]
@illume This is because `sentry-expo` still uses `raven-js` instead of `@sentry/browser`. If I find some time I can update it.

**Comment by illume** [comment]
Ah ok. Thanks for the info :)

**Comment by ricardovf** [comment]
@HazAT i also need that. And if possible, let us set arbitrary fields of the user instead to have to use the extra key, as it makes search easier on the sentry platform. Thanks for the great work!

**Comment by cmacdonnacha** [comment]
Hey @hazAt, just wondering if you've had a chance to update this?

**Comment by HazAT** [comment]
@cmacdonnacha More info here: https://github.com/expo/sentry-expo/pull/58

**Comment by cmacdonnacha** [comment]
Hey Guys, 

Just upgraded to Expo SDk 35 and `sentry-expo`  2.0.0. I am trying to set user using the [Sentry docs](https://docs.sentry.io/enriching-error-data/context/?platform=browser#capturing-the-user) but i'm getting an error `undefined is not an object (evaluating '_sentryExpo.default.configureScope')`

Thanks,
Cathal.

**Comment by cmacdonnacha** [comment]
Actually got this to work by changing my import statement to `import * as Sentry from 'sentry-expo';`

**Comment by cruzach** [comment]
Just tested this on the most recent version of `sentry-expo` on an Expo SDK 36 project, and 
```
Sentry.configureScope(function(scope) {
  scope.setTag("my-tag", "my value");
  scope.setUser({
    id: 42,
    email: "john.doe@example.com"
  });
});
```
works like a charm. Feel free to open up a new issue if you're still having trouble with this, and make sure you're importing how @cmacdonnacha explained :)

**Comment by Edweis** [comment]
Still have the issue today. When using
```javascript
Sentry.configureScope(scope => scope.setUser({ email: emailForSentry }));
```
I end up having some time : 
`undefined is not an object (evaluating 'o.default.configureScope')`
with `"sentry-expo": "^2.0.1"`.

**Comment by bill-pairaktaridis** [comment]
@Edweis how are you importing Sentry? 

Like so? `import * as Sentry from 'sentry-expo';`

**Comment by Joshandrews43** [comment]
I am getting this error in SDK 39

**Comment by moooss** [comment]
I can't use  `Sentry.configureScope` with `sentry-expo@3.0.0`  and higher
It works with `2.1.2`

Import is done this way : 
```js
import * as Sentry from 'sentry-expo'
```

And get this error :
```
TypeError: Sentry.configureScope is not a function. (In 'Sentry.configureScope(function (scope) {
      scope.setUser({
        id: 5,
        email: 'john.doe@example.com'
      });
    })', 'Sentry.configureScope' is undefined)
```

@cruzach would you mind to reopen this issue ?

**Comment by cruzach** [comment]
@moooss please read the [changelog](https://github.com/expo/sentry-expo/blob/master/CHANGELOG.md#-breaking-changes) when you upgrade versions, _especially_ when you upgrade a major version, which always indicates breaking changes. 

You will need to call `Sentry.Native.configureScope` OR import like this:
```
import { Native } from 'sentry-expo';
```

**Comment by moooss** [comment]
Thanks a lot for your answer and really sorry for my misunderstanding.
To be honest I'm not upgrading but using this lib for the first time, didn't see this in the docs, and got mislead by sentry docs and old issues like this one.

Thanks again.

**Comment by cruzach** [comment]
gotchya 👍  no worries

The [docs here](https://docs.expo.io/guides/using-sentry/#install-and-configure-sentry) do specify the namespaced imports, but if you see any other conflicting docs let me know and I'll make sure to update them
